# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Roger Ndaba <rogerndaba@gmail.com>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/06/06 10:56:32 by Roger Ndaba       #+#    #+#              #
#    Updated: 2019/06/06 11:24:01 by Roger Ndaba      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME = replace

CC = clang++ -Wall -Wextra -Werror -std=c++98 -o $(NAME)

FILE = main.cpp

all: $(NAME)

$(NAME):
	@$(CC) $(FILE)
	@printf "\e[1;32mCompiled successfully\e[0m\n"

