# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: roger <rogerndaba@gmail.com>               +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/06/03 14:23:02 by roger             #+#    #+#              #
#    Updated: 2019/06/03 14:23:03 by roger            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = megaphone

CC = clang++ -Wall -Wextra -Werror -o $(NAME)

FILE = megaphone.cpp

all: $(NAME)

$(NAME):
	@$(CC) $(FILE)
	@printf "\e[1;32mCompiled successfully\e[0m\n"

